---
title: "Biodiversity Effects Partition"
author: "Michael Crawford"
output: 
    html_document:
        toc: true
        toc_float: true
        number_section: true
        highlight: zenburn
knit: (function(inputFile, encoding) 
        {
          rmarkdown::render(inputFile, encoding = encoding, output_dir = "markdowns") 
        }
      )
---

<style>
pre {
overflow-x: auto;
}
pre code {
word-wrap: normal;
white-space: pre;
}
</style>

```{r setup, include=FALSE}

options(width = 1000)

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.height = 4,
                      fig.width = 8,
                      size = "small") 

library(data.table)
library(tidyverse)
library(ggthemes)
library(viridis)
library(cowplot)
library(scales)
library(knitr)

```

```{r load-lindsay, echo=FALSE}

setwd("/Users/Theodore/Documents/Dropbox/Work/Projects/SimNet/Modelling_Experiment/data")

load("lindsaymod_trans_exp_out_HPC.rda")

lindsay <- datout %>%
    mutate(Biomass = Productivity) %>%
    select(-Productivity)

rm(datout)

# lindsay ran the 64 species simulation too many times
lindsay_64 <- lindsay %>%
    filter(Ninitial == 64) %>%
    group_by(Model, SeedRain, SpeciesID, Stage, Year) %>%
    filter(Rep == first(Rep))

lindsay_not64 <- lindsay %>%
    filter(Ninitial != 64)

lindsay <- bind_rows(lindsay_64, lindsay_not64) %>%
    ungroup()

lindsay <- lindsay %>%
    mutate(Model = as.character(Model),
           Ninitial = as.numeric(Ninitial),
           Rep = as.numeric(Rep),
           SeedRain = as.factor(SeedRain),
           SpeciesID = as.character(SpeciesID),
           Stage = as.factor(Stage),
           Year = as.numeric(Year),
           Biomass = as.numeric(Biomass))

lindsay <- lindsay %>%
    mutate(Stage = recode(Stage,
                          assembly = "metacommunity",
                          disassembly = "isolation"))

lindsay <- lindsay %>%
    filter(SeedRain %in% c(100))

lindsay <- lindsay %>%
    ungroup() %>% # There shouldn't be groups anyways
    mutate(Biomass = scales::rescale(Biomass,
                                     to = c(0, 100)))

```

```{r load-adam, echo=FALSE}

setwd("/Users/Theodore/Documents/Dropbox/Work/Projects/SimNet/Modelling_Experiment/data")

load("adammod_trans_exp_out_HPC.rda")

adam <- datout %>%
  mutate(Biomass = Productivity) %>%
  select(-Productivity)

rm(datout)

# Adam ran the 64 species simulation too many times
adam_64 <- adam %>%
  filter(Ninitial == 64) %>%
  group_by(Model, SeedRain, SpeciesID, Stage, Year) %>%
  filter(Rep == first(Rep))

adam_not64 <- adam %>%
  filter(Ninitial != 64)

adam <- bind_rows(adam_64, adam_not64) %>%
  ungroup()

adam <- adam %>%
  mutate(Model = as.character(Model),
         Ninitial = as.numeric(Ninitial),
         Rep = as.numeric(Rep),
         SeedRain = as.factor(SeedRain),
         SpeciesID = as.character(SpeciesID),
         Stage = as.factor(Stage),
         Year = as.numeric(Year),
         Biomass = as.numeric(Biomass))

adam <- adam %>%
  mutate(Stage = recode(Stage,
                        assembly = "metacommunity",
                        disassembly = "isolation"))

adam <- adam %>%
  filter(SeedRain %in% c(100))

adam <- adam %>%
  ungroup() %>% # There shouldn't be groups anyways
  mutate(Biomass = scales::rescale(Biomass,
                                   to = c(0, 100)))

```

```{r combine-data, echo=FALSE}

models <- bind_rows(adam, lindsay)

```

# Partitioning biodiversity into complementarity and selection effects
```{r biodiversity-partition}

monocultures <- models %>%
    filter(Ninitial == 1) %>%
    select(-Ninitial, -Rep) %>%
    rename(M_i = Biomass)

d <- inner_join(models, monocultures) %>%
    filter(Ninitial > 1) %>%
    rename(Y_Oi = Biomass)

d <- d %>%
    group_by(Model, Ninitial, Rep, SeedRain, Stage, Year) %>%
    mutate(Y_O = sum(Y_Oi),
           RY_Ei = 1 / Ninitial)

d <- d %>%
    group_by(Model, Ninitial, Rep, SeedRain, Stage, Year, SpeciesID) %>%
    mutate(RY_Oi = Y_Oi / M_i,
           Y_Ei = RY_Ei * M_i)

d <- d %>%
    group_by(Model, Ninitial, Rep, SeedRain, Stage, Year) %>%
    mutate(Y_E = sum(Y_Ei))

d <- d %>%
    group_by(Model, Ninitial, Rep, SeedRain, Stage, Year, SpeciesID) %>%
    mutate(delta.Y = Y_O - Y_E,
           delta.RY_i = RY_Oi - RY_Ei)

d <- d %>%
    group_by(Model, Ninitial, Rep, SeedRain, Stage, Year) %>%
    summarise(complementarity.effect = n() * mean(delta.RY_i) * mean(M_i),
              selection.effect = n() * cov(delta.RY_i, M_i),
              net.biodiversity.effect = complementarity.effect + selection.effect)

```

# Complementarity effects
```{r plot-complementarity}

ggplot(d) +
    geom_line(aes(x = Year,
                  y = complementarity.effect,
                  group = as.factor(Rep)),
              alpha = 1/3) +
    geom_vline(xintercept = 100, 
               linetype = 3) +
    facet_grid(rows = vars(Model),
               cols = vars(Ninitial)) +
    labs(x = "Year",
         y = "Complementarity effect") +
    theme_bw()

```

# Selection effects
```{r plot-selection}

ggplot(d) +
    geom_line(aes(x = Year,
                  y = selection.effect,
                  group = as.factor(Rep)),
              alpha = 1/3) +
    geom_vline(xintercept = 100, 
               linetype = 3) +
    facet_grid(rows = vars(Model),
               cols = vars(Ninitial)) +
    labs(x = "Year",
         y = "Selection effect") +
    theme_bw()

```

# Relationship between complementarity and selection effects
```{r plot-simpler}

d <- d %>%
    filter(Year %in% c(100, 200))

ggplot(d) +
    geom_point(aes(x = complementarity.effect,
                   y = selection.effect,
                   color = as.factor(Ninitial))) +
    geom_hline(yintercept = 0, linetype = 3) +
    geom_vline(xintercept = 0, linetype = 3) +
    facet_grid(cols = vars(Stage),
               rows = vars(Model)) +
    scale_color_viridis(discrete = TRUE) +
    labs(x = "Complementarity effect",
         y = "Selection effect",
         color = "Planted species\nrichness") +
    theme_bw()

```
