---
title: "Adam's model"
author: "VeronikaCeballosN"
output: 
    html_document:
        toc: true
        toc_float: true
        number_section: true
        highlight: zenburn
knit: (function(inputFile, encoding) 
        {
          rmarkdown::render(inputFile, encoding = encoding, output_dir = "markdowns") 
        }
      )
---

## Setup

```{r setup, include=FALSE}

options(width = 1000)

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      #fig.height = 4,
                      #fig.width = 8,
                      size = "small") 

library(data.table)
library(tidyverse)
library(ggthemes)
library(gganimate)
library(viridis) 
library(cowplot)
library(scales)
library(plotly)
library(randomForest)
library(pdp)
```

```{r read-models, echo=TRUE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)); setwd("../")
base_dir          <- getwd()
scripts_dir       <- paste0(base_dir, "/R")
tmp_dir           <- paste0(base_dir, "/tmp")
raw_data_dir      <- paste0(base_dir, "/data/raw")
meta = seq(80, 100)
iso = seq(180, 200)

source(paste0(scripts_dir, "/3readModels.R"))
```

```{r randomForest_4conditions, echo=TRUE}
adam <- adam %>%
    select(-Model, -SeedRain) %>%
    mutate(SpeciesID = as.factor(SpeciesID))

adam_traits <- adam_traits %>%
    mutate(SpeciesID = as.factor(SpeciesID))

adam <- inner_join(adam, adam_traits, by = c("SpeciesID"))

adam.32 <- adam %>%
    filter(Ninitial == 32,
           Year %in% meta) %>%
    mutate(id = row_number()) %>%
    mutate_if(is.character, as.factor) %>%
    select(-SpeciesID, -Ninitial, -Stage, -Rep) 

train <- adam.32 %>% sample_frac(.70)
test <- anti_join(adam.32, train, by = 'id')

train <- train %>% select(-id)
test <- test %>% select(-id)

rf <- randomForest(data = as.data.frame(train),
                                Biomass ~ .,
                                importance = TRUE)

pred <- data.frame(pred = predict(rf, test))
title = paste("correlation: ", round(cor(pred, test$Biomass)[[1]], 2),
              "  |  mean squared error: ", round(mean(rf$mse), 2),
              "  |  R-squared: ", round(mean(rf$rsq), 2),
              sep = "")
pdf(paste0(tmp_dir,"/randomForest/G1C3.pdf"))
varImpPlot(rf, main = title)
#dev.set(dev.next())
while (!is.null(dev.list()))  dev.off()
```

```{r randomForest_4conditions2, echo=TRUE}
adam.32 <- adam %>%
    filter(Ninitial == 32,
           Year %in% iso) %>%
    mutate(id = row_number()) %>%
    mutate_if(is.character, as.factor) %>%
    select(-SpeciesID, -Ninitial, -Stage, -Rep) 

train <- adam.32 %>% sample_frac(.70)
test <- anti_join(adam.32, train, by = 'id')

train <- train %>% select(-id)
test <- test %>% select(-id)

rf <- randomForest(data = as.data.frame(train),
                                Biomass ~ .,
                                importance = TRUE)

pred <- data.frame(pred = predict(rf, test))
title = paste("correlation: ", round(cor(pred, test$Biomass)[[1]], 2),
              "  |  mean squared error: ", round(mean(rf$mse), 2),
              "  |  R-squared: ", round(mean(rf$rsq), 2),
              sep = "")
pdf(paste0(tmp_dir,"/randomForest/G1C4.pdf"))
varImpPlot(rf, main = title)
#dev.set(dev.next())
while (!is.null(dev.list()))  dev.off()
```

```{r randomForest_4conditions3, echo=TRUE}
lindsay <- lindsay %>%
    select(-Model, -SeedRain) %>%
    mutate(SpeciesID = as.factor(SpeciesID))

lindsay_traits <- lindsay_traits %>%
    mutate(SpeciesID = as.factor(SpeciesID))

lindsay <- inner_join(lindsay, lindsay_traits, by = c("SpeciesID"))
modelName1 = "G2C3"
modelName2 = "G2C4"

lindsay.32 <- lindsay %>%
    filter(Ninitial == 8,
           Year %in% meta) %>%
    mutate(id = row_number()) %>%
    mutate_if(is.character, as.factor) %>%
    select(-SpeciesID, -Ninitial, -Stage, -Rep) 

train <- lindsay.32 %>% sample_frac(.70)
test <- anti_join(lindsay.32, train, by = 'id')

train <- train %>% select(-id)
test <- test %>% select(-id)

rf <- randomForest(data = as.data.frame(train),
                                Biomass ~ .,
                                importance = TRUE)

pred <- data.frame(pred = predict(rf, test))
title = paste("correlation: ", round(cor(pred, test$Biomass)[[1]], 2),
              "  |  mean squared error: ", round(mean(rf$mse), 2),
              "  |  R-squared: ", round(mean(rf$rsq), 2),
              sep = "")
pdf(paste0(tmp_dir,"/randomForest/",modelName1,".pdf"))
varImpPlot(rf, main = title)
#dev.set(dev.next())
while (!is.null(dev.list()))  dev.off()

lindsay.32 <- lindsay %>%
    filter(Ninitial == 8,
           Year %in% iso) %>%
    mutate(id = row_number()) %>%
    mutate_if(is.character, as.factor) %>%
    select(-SpeciesID, -Ninitial, -Stage, -Rep) 

train <- lindsay.32 %>% sample_frac(.70)
test <- anti_join(lindsay.32, train, by = 'id')

train <- train %>% select(-id)
test <- test %>% select(-id)

rf <- randomForest(data = as.data.frame(train),
                                Biomass ~ .,
                                importance = TRUE)

pred <- data.frame(pred = predict(rf, test))
title = paste("correlation: ", round(cor(pred, test$Biomass)[[1]], 2),
              "  |  mean squared error: ", round(mean(rf$mse), 2),
              "  |  R-squared: ", round(mean(rf$rsq), 2),
              sep = "")
pdf(paste0(tmp_dir,"/randomForest/",modelName2,".pdf"))
varImpPlot(rf, main = title)
#dev.set(dev.next())
while (!is.null(dev.list()))  dev.off()
```

```{r randomForest_4conditions, echo=TRUE}
troll <- troll %>%
    select(-Model, -SeedRain) %>%
    mutate(SpeciesID = as.factor(SpeciesID))

troll_traits <- troll_traits %>%
    mutate(SpeciesID = as.factor(SpeciesID))

troll <- inner_join(troll, troll_traits, by = c("SpeciesID"))

troll <- troll %>%
    mutate(h_realmax = hmax * dmax / (dmax + ah)) %>%
    select(-hmax, -ah)

modelName1 = "F2C3"
modelName2 = "F2C4"

troll.32 <- troll %>%
    filter(Ninitial == 8,
           Year %in% meta) %>%
    mutate(id = row_number()) %>%
    mutate_if(is.character, as.factor) %>%
    select(-SpeciesID, -Ninitial, -Stage, -Rep) 

train <- troll.32 %>% sample_frac(.70)
test <- anti_join(troll.32, train, by = 'id')

train <- train %>% select(-id)
test <- test %>% select(-id)

rf <- randomForest(data = as.data.frame(train),
                                Biomass ~ .,
                                importance = TRUE)

pred <- data.frame(pred = predict(rf, test))
title = paste("correlation: ", round(cor(pred, test$Biomass)[[1]], 2),
              "  |  mean squared error: ", round(mean(rf$mse), 2),
              "  |  R-squared: ", round(mean(rf$rsq), 2),
              sep = "")
pdf(paste0(tmp_dir,"/randomForest/",modelName1,".pdf"))
varImpPlot(rf, main = title)
#dev.set(dev.next())
while (!is.null(dev.list()))  dev.off()

troll.32 <- troll %>%
    filter(Ninitial == 8,
           Year %in% iso) %>%
    mutate(id = row_number()) %>%
    mutate_if(is.character, as.factor) %>%
    select(-SpeciesID, -Ninitial, -Stage, -Rep) 

train <- troll.32 %>% sample_frac(.70)
test <- anti_join(troll.32, train, by = 'id')

train <- train %>% select(-id)
test <- test %>% select(-id)

rf <- randomForest(data = as.data.frame(train),
                                Biomass ~ .,
                                importance = TRUE)

pred <- data.frame(pred = predict(rf, test))
title = paste("correlation: ", round(cor(pred, test$Biomass)[[1]], 2),
              "  |  mean squared error: ", round(mean(rf$mse), 2),
              "  |  R-squared: ", round(mean(rf$rsq), 2),
              sep = "")
pdf(paste0(tmp_dir,"/randomForest/",modelName2,".pdf"))
varImpPlot(rf, main = title)
#dev.set(dev.next())
while (!is.null(dev.list()))  dev.off()
```

