# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs dissmodel
#' @name simulate
#' @param expParFilename Name of input file
#' @return Time series of biomass and productivity of all species
NULL

simulate <- function(expParFilename) {
    .Call(`_dissmodelr_simulate`, expParFilename)
}

