install.packages("assertthat",dependencies = TRUE)
install.packages("rstan",dependencies = TRUE)
install.packages("brms",dependencies = TRUE)
install.packages("tidybayes",dependencies = TRUE)
install.packages("modelr",dependencies = TRUE)
install.packages("sjstats",dependencies = TRUE)
install.packages("sjPlot",dependencies = TRUE)
install.packages("data.table",dependencies = TRUE)
install.packages("tidyverse",dependencies = TRUE)
install.packages("FD",dependencies = TRUE)
install.packages("cowplot",dependencies = TRUE)
install.packages("ggthemes",dependencies = TRUE)
install.packages("rsample",dependencies = TRUE)
install.packages("lmodel2",dependencies = TRUE)
install.packages("infer",dependencies = TRUE)
install.packages("scales",dependencies = TRUE)
install.packages("party",dependencies = TRUE)

# To use ggbiplot for PCA results visualization:
install.packages("devtools",dependencies = TRUE)
library(devtools)
install_github("vqv/ggbiplot")
