---
title: "Extra graphs"
output: 
    rmarkdown::html_vignette:
        fig_width: 7
        fig_height: 10
knit: (function(inputFile, encoding) 
        {
          rmarkdown::render(inputFile, encoding = encoding, output_dir = "markdowns") 
        }
      )
---

<style>
pre 
{
    overflow-x: auto;
}
pre code 
{
    word-wrap: normal;
    white-space: pre;
}
</style>

```{r setup-knitr, include = FALSE}

options(width = 1000)

library(knitr)
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      size = "small",
                      dev = "png") 

```

```{r setup, include=FALSE}

library(tidyverse)
library(knitr)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
setwd("../data/brms_models")

models <- readRDS(file = "productivity_brms_models.rds") %>% 
    filter(measure == "Shannon") %>%
    select(Model, data, measure) %>%
    unnest(data)

```

****************************************************************************************************
# Figure 1

```{r fig-1}

d <- models %>%
    group_by(Model, Ninitial, Rep) %>%
    arrange(Model, Ninitial, Rep, Stage) %>%
    mutate(delta.Shannon = (Shannon - lag(Shannon)) / lag(Shannon) * 100,
           delta.biomass = (biomass - lag(biomass)) / lag(biomass) * 100) %>%
    filter(!is.na(delta.Shannon), 
           Ninitial != 1)

ggplot(d) +
    geom_point(aes(x = delta.Shannon,
                   y = delta.biomass,
                   color = Ninitial),
               alpha = 0.8) +
    geom_hline(yintercept = 0, color = "darkgray") +
    geom_vline(xintercept = 0, color = "darkgray") +
    facet_wrap(facets = vars(Model), ncol = 2) +
    xlim(c(-100, 100)) +
    ylim(c(-100, 100)) +
    labs(x = "Change in Shannon (%)",
         y = "Change in total biomass (%)") +
    theme_bw(10) +
    theme(aspect.ratio = 1)

```
Percent change in community structure (Shannon diversity and biomass) after seed inflow is discontinued. 
